services:
  postgres:
    image: postgres:17-alpine
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: extend_leaderboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d extend_leaderboard"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres_data:
    driver: local
