services:
  atoyr:
    build:
      context: .
    image: atoyr:latest
    container_name: atoyr
    ports:
      - "80:80"
    env_file:
      - packages/server/.env.production
    environment:
      PORT: 3000
      WORDS_PATH: data/words.json
      DATABASE_PATH: data/db.sqlite3
      ENV: production
    volumes:
      - ./packages/server/data:/app/server/data

