// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: leaderboard/v1/leaderboard.proto

package leaderboardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *AddSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AddSessionRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type AddSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{1}
}

type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{3}
}

type UpsertEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttempts int32                  `protobuf:"varint,4,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntryRequest) Reset() {
	*x = UpsertEntryRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntryRequest) ProtoMessage() {}

func (x *UpsertEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntryRequest.ProtoReflect.Descriptor instead.
func (*UpsertEntryRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertEntryRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *UpsertEntryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertEntryRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpsertEntryRequest) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *UpsertEntryRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *UpsertEntryRequest) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type UpsertEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntryResponse) Reset() {
	*x = UpsertEntryResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntryResponse) ProtoMessage() {}

func (x *UpsertEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntryResponse.ProtoReflect.Descriptor instead.
func (*UpsertEntryResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{5}
}

var File_leaderboard_v1_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_v1_leaderboard_proto_rawDesc = "" +
	"\n" +
	" leaderboard/v1/leaderboard.proto\x12\x14atoyr.leaderboard.v1\"~\n" +
	"\x11AddSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"\x14\n" +
	"\x12AddSessionResponse\"5\n" +
	"\x14RemoveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RemoveSessionResponse\"\xbb\x01\n" +
	"\x12UpsertEntryRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12%\n" +
	"\x0etotal_attempts\x18\x04 \x01(\x05R\rtotalAttempts\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x01R\baccuracy\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\x03R\n" +
	"finishedAt\"\x15\n" +
	"\x13UpsertEntryResponse2\xc3\x02\n" +
	"\x12LeaderboardService\x12_\n" +
	"\n" +
	"AddSession\x12'.atoyr.leaderboard.v1.AddSessionRequest\x1a(.atoyr.leaderboard.v1.AddSessionResponse\x12h\n" +
	"\rRemoveSession\x12*.atoyr.leaderboard.v1.RemoveSessionRequest\x1a+.atoyr.leaderboard.v1.RemoveSessionResponse\x12b\n" +
	"\vUpsertEntry\x12(.atoyr.leaderboard.v1.UpsertEntryRequest\x1a).atoyr.leaderboard.v1.UpsertEntryResponseB:Z8extend-event-handler/pkg/pb/leaderboard/v1;leaderboardv1b\x06proto3"

var (
	file_leaderboard_v1_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_v1_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_v1_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_v1_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_v1_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_v1_leaderboard_proto_rawDescData
}

var file_leaderboard_v1_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_leaderboard_v1_leaderboard_proto_goTypes = []any{
	(*AddSessionRequest)(nil),     // 0: atoyr.leaderboard.v1.AddSessionRequest
	(*AddSessionResponse)(nil),    // 1: atoyr.leaderboard.v1.AddSessionResponse
	(*RemoveSessionRequest)(nil),  // 2: atoyr.leaderboard.v1.RemoveSessionRequest
	(*RemoveSessionResponse)(nil), // 3: atoyr.leaderboard.v1.RemoveSessionResponse
	(*UpsertEntryRequest)(nil),    // 4: atoyr.leaderboard.v1.UpsertEntryRequest
	(*UpsertEntryResponse)(nil),   // 5: atoyr.leaderboard.v1.UpsertEntryResponse
}
var file_leaderboard_v1_leaderboard_proto_depIdxs = []int32{
	0, // 0: atoyr.leaderboard.v1.LeaderboardService.AddSession:input_type -> atoyr.leaderboard.v1.AddSessionRequest
	2, // 1: atoyr.leaderboard.v1.LeaderboardService.RemoveSession:input_type -> atoyr.leaderboard.v1.RemoveSessionRequest
	4, // 2: atoyr.leaderboard.v1.LeaderboardService.UpsertEntry:input_type -> atoyr.leaderboard.v1.UpsertEntryRequest
	1, // 3: atoyr.leaderboard.v1.LeaderboardService.AddSession:output_type -> atoyr.leaderboard.v1.AddSessionResponse
	3, // 4: atoyr.leaderboard.v1.LeaderboardService.RemoveSession:output_type -> atoyr.leaderboard.v1.RemoveSessionResponse
	5, // 5: atoyr.leaderboard.v1.LeaderboardService.UpsertEntry:output_type -> atoyr.leaderboard.v1.UpsertEntryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leaderboard_v1_leaderboard_proto_init() }
func file_leaderboard_v1_leaderboard_proto_init() {
	if File_leaderboard_v1_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_v1_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_v1_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_v1_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_v1_leaderboard_proto = out.File
	file_leaderboard_v1_leaderboard_proto_goTypes = nil
	file_leaderboard_v1_leaderboard_proto_depIdxs = nil
}
