/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/game/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['StartGameRequest'];
        };
      };
      responses: {
        /** @description Game started successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StartGameResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/game/continue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Game continued successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StartGameResponse'];
          };
        };
        /** @description Game session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/game/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SubmitAnswerRequest'];
        };
      };
      responses: {
        /** @description Answer submitted successfully, response contains the next question and updated game state */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SubmitAnswerResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Game session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/game/sse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE stream for real-time game updates */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/event-stream': string;
          };
        };
        /** @description Game session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          limit?: number;
          mode?: components['schemas']['SessionMode'];
          topic?: components['schemas']['SessionTopic'];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Leaderboard data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetLeaderboardResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/leaderboard/percentile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          mode?: components['schemas']['SessionMode'];
          topic?: components['schemas']['SessionTopic'];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Percentile data retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetLeaderboardPercentileResponse'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Game session not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        [key: string]: unknown;
      };
    };
    StartGameRequest: {
      autoVoice?: boolean;
      mode: components['schemas']['SessionMode'];
      topic: components['schemas']['SessionTopic'];
      itemsUsed: string[];
    };
    StartGameResponse: {
      /** Format: uuid */
      sessionId: string;
      mode: components['schemas']['SessionMode'];
      topic: components['schemas']['SessionTopic'];
      /** @example en-US */
      lang: string;
      /** @example lpeap */
      scrambledWord: string;
      /** @example A fruit that is often red or green. */
      scrambledWordDefinition: string;
      /** Format: uuid */
      token: string;
      /**
       * Format: int32
       * @example 60
       */
      remainingSeconds: number;
      autoVoice: boolean;
    };
    SubmitAnswerRequest: {
      /** @example apple */
      answer: string;
      /** Format: uuid */
      token: string;
    };
    SubmitAnswerResponse: {
      correct: boolean;
      /** @example lpeap */
      scrambledWord: string;
      /** @example A fruit that is often red or green. */
      scrambledWordDefinition: string;
      correctAttemptTimestamps: string[][];
      /** Format: uuid */
      token: string;
      /**
       * Format: int32
       * @example 10
       */
      score: number;
      /**
       * Format: int32
       * @example 2
       */
      attempts: number;
      /**
       * Format: int32
       * @example 45
       */
      remainingSeconds: number;
    };
    GetLeaderboardResponse: {
      entries: components['schemas']['LeaderboardEntry'][];
      /** Format: int64 */
      total: number;
    };
    GetLeaderboardPercentileResponse: {
      percentile: number;
    };
    LeaderboardEntry: {
      /** Format: uuid */
      id: string;
      topic: components['schemas']['SessionTopic'];
      /** @example false */
      isSessionSameAsCurrentUser?: boolean;
      /**
       * Format: int32
       * @example 1
       */
      rank: number;
      /**
       * Format: int32
       * @example 100
       */
      score: number;
      /**
       * Format: int32
       * @example 5
       */
      totalAttempts: number;
      /**
       * Format: float
       * @example 0.8
       */
      accuracy: number;
      /**
       * Format: int64
       * @example 1627847284
       */
      timestamp: number;
    };
    /** @enum {string} */
    SessionMode: 'vanilla' | 'blind';
    /** @enum {string} */
    SessionTopic: 'english-words' | 'indonesian-politician-quotes';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type ErrorResponse = components['schemas']['ErrorResponse'];
export type StartGameRequest = components['schemas']['StartGameRequest'];
export type StartGameResponse = components['schemas']['StartGameResponse'];
export type SubmitAnswerRequest = components['schemas']['SubmitAnswerRequest'];
export type SubmitAnswerResponse = components['schemas']['SubmitAnswerResponse'];
export type GetLeaderboardResponse = components['schemas']['GetLeaderboardResponse'];
export type GetLeaderboardPercentileResponse = components['schemas']['GetLeaderboardPercentileResponse'];
export type LeaderboardEntry = components['schemas']['LeaderboardEntry'];
export type SessionMode = components['schemas']['SessionMode'];
export type SessionTopic = components['schemas']['SessionTopic'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
