// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: leaderboard/v1/leaderboard.proto

package leaderboardv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetLeaderboardRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttempts int32                  `protobuf:"varint,4,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *LeaderboardEntry) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LeaderboardEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetLeaderboardResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPercentileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPercentileRequest) Reset() {
	*x = GetPercentileRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPercentileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPercentileRequest) ProtoMessage() {}

func (x *GetPercentileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPercentileRequest.ProtoReflect.Descriptor instead.
func (*GetPercentileRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetPercentileRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetPercentileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPercentileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentile    float64                `protobuf:"fixed64,1,opt,name=percentile,proto3" json:"percentile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPercentileResponse) Reset() {
	*x = GetPercentileResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPercentileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPercentileResponse) ProtoMessage() {}

func (x *GetPercentileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPercentileResponse.ProtoReflect.Descriptor instead.
func (*GetPercentileResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetPercentileResponse) GetPercentile() float64 {
	if x != nil {
		return x.Percentile
	}
	return 0
}

type AddSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *AddSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AddSessionRequest) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type AddSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{6}
}

type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{8}
}

type UpsertEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttempts int32                  `protobuf:"varint,4,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntryRequest) Reset() {
	*x = UpsertEntryRequest{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntryRequest) ProtoMessage() {}

func (x *UpsertEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntryRequest.ProtoReflect.Descriptor instead.
func (*UpsertEntryRequest) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertEntryRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *UpsertEntryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpsertEntryRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpsertEntryRequest) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *UpsertEntryRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *UpsertEntryRequest) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type UpsertEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntryResponse) Reset() {
	*x = UpsertEntryResponse{}
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntryResponse) ProtoMessage() {}

func (x *UpsertEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_v1_leaderboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntryResponse.ProtoReflect.Descriptor instead.
func (*UpsertEntryResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_v1_leaderboard_proto_rawDescGZIP(), []int{10}
}

var File_leaderboard_v1_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_v1_leaderboard_proto_rawDesc = "" +
	"\n" +
	" leaderboard/v1/leaderboard.proto\x12\x14atoyr.leaderboard.v1\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\x15GetLeaderboardRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xb6\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12%\n" +
	"\x0etotal_attempts\x18\x04 \x01(\x05R\rtotalAttempts\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x01R\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"p\n" +
	"\x16GetLeaderboardResponse\x12@\n" +
	"\aentries\x18\x01 \x03(\v2&.atoyr.leaderboard.v1.LeaderboardEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"C\n" +
	"\x14GetPercentileRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"7\n" +
	"\x15GetPercentileResponse\x12\x1e\n" +
	"\n" +
	"percentile\x18\x01 \x01(\x01R\n" +
	"percentile\"~\n" +
	"\x11AddSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"\x14\n" +
	"\x12AddSessionResponse\"5\n" +
	"\x14RemoveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RemoveSessionResponse\"\xbb\x01\n" +
	"\x12UpsertEntryRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12%\n" +
	"\x0etotal_attempts\x18\x04 \x01(\x05R\rtotalAttempts\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x01R\baccuracy\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\x03R\n" +
	"finishedAt\"\x15\n" +
	"\x13UpsertEntryResponse2\xfc\x04\n" +
	"\x12LeaderboardService\x12\x84\x01\n" +
	"\x0eGetLeaderboard\x12+.atoyr.leaderboard.v1.GetLeaderboardRequest\x1a,.atoyr.leaderboard.v1.GetLeaderboardResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/leaderboard\x12\x8c\x01\n" +
	"\rGetPercentile\x12*.atoyr.leaderboard.v1.GetPercentileRequest\x1a+.atoyr.leaderboard.v1.GetPercentileResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/leaderboard/percentile\x12_\n" +
	"\n" +
	"AddSession\x12'.atoyr.leaderboard.v1.AddSessionRequest\x1a(.atoyr.leaderboard.v1.AddSessionResponse\x12h\n" +
	"\rRemoveSession\x12*.atoyr.leaderboard.v1.RemoveSessionRequest\x1a+.atoyr.leaderboard.v1.RemoveSessionResponse\x12\x84\x01\n" +
	"\vUpsertEntry\x12(.atoyr.leaderboard.v1.UpsertEntryRequest\x1a).atoyr.leaderboard.v1.UpsertEntryResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/leaderboard/entryB8Z6extend-leaderboard/pkg/pb/leaderboard/v1;leaderboardv1b\x06proto3"

var (
	file_leaderboard_v1_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_v1_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_v1_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_v1_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_v1_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_v1_leaderboard_proto_rawDescData
}

var file_leaderboard_v1_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_leaderboard_v1_leaderboard_proto_goTypes = []any{
	(*GetLeaderboardRequest)(nil),  // 0: atoyr.leaderboard.v1.GetLeaderboardRequest
	(*LeaderboardEntry)(nil),       // 1: atoyr.leaderboard.v1.LeaderboardEntry
	(*GetLeaderboardResponse)(nil), // 2: atoyr.leaderboard.v1.GetLeaderboardResponse
	(*GetPercentileRequest)(nil),   // 3: atoyr.leaderboard.v1.GetPercentileRequest
	(*GetPercentileResponse)(nil),  // 4: atoyr.leaderboard.v1.GetPercentileResponse
	(*AddSessionRequest)(nil),      // 5: atoyr.leaderboard.v1.AddSessionRequest
	(*AddSessionResponse)(nil),     // 6: atoyr.leaderboard.v1.AddSessionResponse
	(*RemoveSessionRequest)(nil),   // 7: atoyr.leaderboard.v1.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),  // 8: atoyr.leaderboard.v1.RemoveSessionResponse
	(*UpsertEntryRequest)(nil),     // 9: atoyr.leaderboard.v1.UpsertEntryRequest
	(*UpsertEntryResponse)(nil),    // 10: atoyr.leaderboard.v1.UpsertEntryResponse
}
var file_leaderboard_v1_leaderboard_proto_depIdxs = []int32{
	1,  // 0: atoyr.leaderboard.v1.GetLeaderboardResponse.entries:type_name -> atoyr.leaderboard.v1.LeaderboardEntry
	0,  // 1: atoyr.leaderboard.v1.LeaderboardService.GetLeaderboard:input_type -> atoyr.leaderboard.v1.GetLeaderboardRequest
	3,  // 2: atoyr.leaderboard.v1.LeaderboardService.GetPercentile:input_type -> atoyr.leaderboard.v1.GetPercentileRequest
	5,  // 3: atoyr.leaderboard.v1.LeaderboardService.AddSession:input_type -> atoyr.leaderboard.v1.AddSessionRequest
	7,  // 4: atoyr.leaderboard.v1.LeaderboardService.RemoveSession:input_type -> atoyr.leaderboard.v1.RemoveSessionRequest
	9,  // 5: atoyr.leaderboard.v1.LeaderboardService.UpsertEntry:input_type -> atoyr.leaderboard.v1.UpsertEntryRequest
	2,  // 6: atoyr.leaderboard.v1.LeaderboardService.GetLeaderboard:output_type -> atoyr.leaderboard.v1.GetLeaderboardResponse
	4,  // 7: atoyr.leaderboard.v1.LeaderboardService.GetPercentile:output_type -> atoyr.leaderboard.v1.GetPercentileResponse
	6,  // 8: atoyr.leaderboard.v1.LeaderboardService.AddSession:output_type -> atoyr.leaderboard.v1.AddSessionResponse
	8,  // 9: atoyr.leaderboard.v1.LeaderboardService.RemoveSession:output_type -> atoyr.leaderboard.v1.RemoveSessionResponse
	10, // 10: atoyr.leaderboard.v1.LeaderboardService.UpsertEntry:output_type -> atoyr.leaderboard.v1.UpsertEntryResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_leaderboard_v1_leaderboard_proto_init() }
func file_leaderboard_v1_leaderboard_proto_init() {
	if File_leaderboard_v1_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_v1_leaderboard_proto_rawDesc), len(file_leaderboard_v1_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_v1_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_v1_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_v1_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_v1_leaderboard_proto = out.File
	file_leaderboard_v1_leaderboard_proto_goTypes = nil
	file_leaderboard_v1_leaderboard_proto_depIdxs = nil
}
