// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: atoyr/events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_atoyr_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_atoyr_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_atoyr_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SessionStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStarted) Reset() {
	*x = SessionStarted{}
	mi := &file_atoyr_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStarted) ProtoMessage() {}

func (x *SessionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_atoyr_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStarted.ProtoReflect.Descriptor instead.
func (*SessionStarted) Descriptor() ([]byte, []int) {
	return file_atoyr_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStarted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStarted) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionStarted) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionStarted) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type SessionFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	TotalAttempts int32                  `protobuf:"varint,5,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFinished) Reset() {
	*x = SessionFinished{}
	mi := &file_atoyr_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFinished) ProtoMessage() {}

func (x *SessionFinished) ProtoReflect() protoreflect.Message {
	mi := &file_atoyr_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFinished.ProtoReflect.Descriptor instead.
func (*SessionFinished) Descriptor() ([]byte, []int) {
	return file_atoyr_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *SessionFinished) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionFinished) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionFinished) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionFinished) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SessionFinished) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *SessionFinished) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *SessionFinished) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

var File_atoyr_events_v1_events_proto protoreflect.FileDescriptor

const file_atoyr_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1catoyr/events/v1/events.proto\x12\x0fatoyr.events.v1\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\rEventEnvelope\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"{\n" +
	"\x0eSessionStarted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"\xd7\x01\n" +
	"\x0fSessionFinished\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12%\n" +
	"\x0etotal_attempts\x18\x05 \x01(\x05R\rtotalAttempts\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x01R\baccuracy\x12\x1f\n" +
	"\vfinished_at\x18\a \x01(\x03R\n" +
	"finishedAt2V\n" +
	"\x11AtoyrEventService\x12A\n" +
	"\aOnEvent\x12\x1e.atoyr.events.v1.EventEnvelope\x1a\x16.google.protobuf.EmptyB6Z4extend-event-handler/pkg/pb/atoyr/events/v1;eventsv1b\x06proto3"

var (
	file_atoyr_events_v1_events_proto_rawDescOnce sync.Once
	file_atoyr_events_v1_events_proto_rawDescData []byte
)

func file_atoyr_events_v1_events_proto_rawDescGZIP() []byte {
	file_atoyr_events_v1_events_proto_rawDescOnce.Do(func() {
		file_atoyr_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atoyr_events_v1_events_proto_rawDesc), len(file_atoyr_events_v1_events_proto_rawDesc)))
	})
	return file_atoyr_events_v1_events_proto_rawDescData
}

var file_atoyr_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_atoyr_events_v1_events_proto_goTypes = []any{
	(*EventEnvelope)(nil),   // 0: atoyr.events.v1.EventEnvelope
	(*SessionStarted)(nil),  // 1: atoyr.events.v1.SessionStarted
	(*SessionFinished)(nil), // 2: atoyr.events.v1.SessionFinished
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_atoyr_events_v1_events_proto_depIdxs = []int32{
	0, // 0: atoyr.events.v1.AtoyrEventService.OnEvent:input_type -> atoyr.events.v1.EventEnvelope
	3, // 1: atoyr.events.v1.AtoyrEventService.OnEvent:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_atoyr_events_v1_events_proto_init() }
func file_atoyr_events_v1_events_proto_init() {
	if File_atoyr_events_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atoyr_events_v1_events_proto_rawDesc), len(file_atoyr_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atoyr_events_v1_events_proto_goTypes,
		DependencyIndexes: file_atoyr_events_v1_events_proto_depIdxs,
		MessageInfos:      file_atoyr_events_v1_events_proto_msgTypes,
	}.Build()
	File_atoyr_events_v1_events_proto = out.File
	file_atoyr_events_v1_events_proto_goTypes = nil
	file_atoyr_events_v1_events_proto_depIdxs = nil
}
