// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.9
// source: atoyr/events/v1/events.proto

package eventsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AtoyrEventService_OnEvent_FullMethodName = "/atoyr.events.v1.AtoyrEventService/OnEvent"
)

// AtoyrEventServiceClient is the client API for AtoyrEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtoyrEventServiceClient interface {
	OnEvent(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type atoyrEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAtoyrEventServiceClient(cc grpc.ClientConnInterface) AtoyrEventServiceClient {
	return &atoyrEventServiceClient{cc}
}

func (c *atoyrEventServiceClient) OnEvent(ctx context.Context, in *EventEnvelope, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AtoyrEventService_OnEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtoyrEventServiceServer is the server API for AtoyrEventService service.
// All implementations should embed UnimplementedAtoyrEventServiceServer
// for forward compatibility.
type AtoyrEventServiceServer interface {
	OnEvent(context.Context, *EventEnvelope) (*emptypb.Empty, error)
}

// UnimplementedAtoyrEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAtoyrEventServiceServer struct{}

func (UnimplementedAtoyrEventServiceServer) OnEvent(context.Context, *EventEnvelope) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnEvent not implemented")
}
func (UnimplementedAtoyrEventServiceServer) testEmbeddedByValue() {}

// UnsafeAtoyrEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtoyrEventServiceServer will
// result in compilation errors.
type UnsafeAtoyrEventServiceServer interface {
	mustEmbedUnimplementedAtoyrEventServiceServer()
}

func RegisterAtoyrEventServiceServer(s grpc.ServiceRegistrar, srv AtoyrEventServiceServer) {
	// If the following call panics, it indicates UnimplementedAtoyrEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AtoyrEventService_ServiceDesc, srv)
}

func _AtoyrEventService_OnEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtoyrEventServiceServer).OnEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtoyrEventService_OnEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtoyrEventServiceServer).OnEvent(ctx, req.(*EventEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

// AtoyrEventService_ServiceDesc is the grpc.ServiceDesc for AtoyrEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AtoyrEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atoyr.events.v1.AtoyrEventService",
	HandlerType: (*AtoyrEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnEvent",
			Handler:    _AtoyrEventService_OnEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoyr/events/v1/events.proto",
}
