services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - AB_CLIENT_ID=${AB_CLIENT_ID}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET}
      - AB_BASE_URL=${AB_BASE_URL}
      - AB_NAMESPACE=${AB_NAMESPACE}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans
      - LEADERBOARD_ADDR=host.docker.internal:6565
    extra_hosts:
      - host.docker.internal:host-gateway
