services:
  app:
    build: .
    ports:
      - "6566:6566"
      - "8081:8081"
    environment:
      - GRPC_SERVER_PORT=6566
      - METRICS_PORT=8081
      - AB_CLIENT_ID=${AB_CLIENT_ID}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET}
      - AB_BASE_URL=${AB_BASE_URL}
      - AB_NAMESPACE=${AB_NAMESPACE}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans
      - LEADERBOARD_ADDR=host.docker.internal:6565
    extra_hosts:
      - host.docker.internal:host-gateway
